version: "2"
services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3.6-management
    ports:
        - "5672:5673"
        - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  base:
    container_name: basic-example-service
    image: nameko/basic-example:dev
    depends_on:
      - rabbit
    ports:
        - "8000:8000"
        - "3000:3000"
    links:
        - "rabbit:rabbitmq"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"